#!/bin/bash
#
#SBATCH --job-name=OmnicorpIdentifyVersions
#SBATCH --output=identify-versions/log-output-%A.txt
#SBATCH --error=identify-versions/log-error-%A.txt
#SBATCH --cpus-per-task 32
#SBATCH --mem=50000
#SBATCH --time=12:00:00
#SBATCH --mail-user=gaurav@renci.org

set -e # Exit immediately if a pipeline fails.

export JAVA_OPTS="-Xmx50G"

echo "Starting IdentifyVersions, writing outputs to identify-versions/"
sbt "runMain org.renci.chemotext.IdentifyVersions"
echo "Processing complete."
