import itertools
from collections import defaultdict

#This script was generated by copilot from the following comment
# I had to add the imports
# I had to add the run function
# I also had to add the if __name__ == "__main__" block
# Most importantly, I had to make sure that the curies were sorted before calculating the pair combinations.
# (TBH, I dont know if that was necessary, but I think it was, otherwise you're depending on getting things out of
# different sets in the same order, which is pretty unlikely)
# Note also that it thinks we can store everything here in memory which ....


# Read in a two column tab delimited file where the first column is a curie and the second colum is a pmid
# Produce a file containing each curie and the number of pmids it is associated with
# Produce a file contining each pmid and the number of curies it is associated with
# Count the number of unique curie pairs that share a pmid


def run(infilename):
    curie_to_pmids = defaultdict(set)
    pmid_to_curies = defaultdict(set)
    with open(infilename, "r") as inf:
        for line in inf:
            curie, pmid = line.strip().split("\t")
            curie_to_pmids[curie].add(pmid)
            pmid_to_curies[pmid].add(curie)
    with open("curie_to_pmids.txt", "w") as outf:
        outf.write("concept\tpublication_count\n")
        for curie, pmids in curie_to_pmids.items():
            outf.write(f"{curie}\t{len(pmids)}\n")
    with open("pmid_to_curies.txt", "w") as outf:
        for pmid, curies in pmid_to_curies.items():
            outf.write(f"{pmid}\t{len(curies)}\n")
    curie_pairs = defaultdict(int)
    for pmid, curies in pmid_to_curies.items():
        for curie1, curie2 in itertools.combinations(curies, 2):
            curie_pairs[frozenset([curie1, curie2])] += 1
    with open("curie_pairs.txt", "w") as outf:
        outf.write("src_concept\tdest_concept\tpublication_count\n")
        for (curie1, curie2), count in curie_pairs.items():
            outf.write(f"{curie1}\t{curie2}\t{count}\n")
    print(f"number of unique curie pairs: {len(curie_pairs)}")

if __name__ == '__main__':
    #run("omnicorp_output/annotation.txt")
    run("/Users/bizon/Projects/ranking-agent/aragorn-ranker/tests/OmnicorpTestData/all.tsv")
